baseurl = "https://www.nollaversio.fi/blog/public/"
languageCode = "fi-fi"
title = "Nollaversio IT"

[taxonomies]
  tag = "tags"

[sections]
  laravel = "Laravel"
  nodejs = "Nodejs"
  electron="Electron"
  arch="Arkkitehtuuri"
  vue="VueJS"
  misc="Muut"
